Improve usage

diff --git a/image/kubes/create-k8s-pipe-job b/image/kubes/create-k8s-pipe-job
--- a/image/kubes/create-k8s-pipe-job
+++ b/image/kubes/create-k8s-pipe-job
@@ -31,19 +31,21 @@ my_eval() {
 usage() {
     echo $1
     echo
-    echo "Usage: $0 -p <pipe-definition-yaml-file> [-a] [-d] [-s] [-v] [-t <image:tag>]" 1>&2
+    echo "Usage: $0 -p <pipe-definition-yaml-file> [-a] [-d] [-s] [-t <image:tag>] [-v]" 1>&2
     echo ""
     echo "   Script to output a Kubernetes configMap and job that will run the "
     echo "   supplied Halfpipe pipe (yaml) file."
     echo ""
-    echo "   - Use -p to supply the HalfPipe pipe .yaml file"
-    echo "   - Use -a to 'kubectl apply' the yaml generated by this script to your current cluster (or use kubectl yourself)"
-    echo "   - Use -d to 'kubectl delete' the yaml generated by this script from your current cluster (or use kubectl yourself)"
-    echo "   - Use -s to DISABLE deployment of HalfPipe connections to a Kubernetes secret (see ${generate_connections_script})"
-    echo "   - Use -t to override the Docker image:tag for Halfpipe (default: $default_halfpipe_image_tag)"
-    echo "   - Use -v to enable debug output"
+    echo "   where:"
+
+    echo "   -p supplies the HalfPipe pipe .yaml file"
+    echo "   -a will 'kubectl apply' the yaml generated by this script to your current cluster (or use kubectl yourself)"
+    echo "   -d will 'kubectl delete' the yaml generated by this script from your current cluster (or use kubectl yourself)"
+    echo "   -s disables deployment of HalfPipe connections to a Kubernetes secret (see ${generate_connections_script})"
+    echo "   -t overrides the Docker image:tag for HalfPipe (default: $default_halfpipe_image_tag)"
+    echo "   -v enables debug output"
     echo ""
-    echo "   See the Halfpipe '-o' flag available in commands like 'cp' and 'sync' to generate the required definition file"
+    echo "   See the HalfPipe '-o' flag available in commands like 'cp' and 'sync' to generate the required definition file"
     echo "   Capture the output of this script in source control or, to deploy directly to your cluster, use the -a flag"
     echo "   Note that the name of the supplied definition file becomes the Kubernetes job name"
     echo
